<div class="panel block" ng-click="toggleActiveBlock(block)" ng-class="{  'panel-success': block.phases.indexOf('S') !== -1 && block.phases.length === 1,
                                                                'panel-warning': block.phases.indexOf('C') !== -1 && block.phases.length === 1,
                                                                'panel-danger': block.phases.indexOf('E') !== -1 && block.phases.length === 1,
                                                                'panel-primary' : (block.phases.indexOf('+') !== -1 || block.phases.indexOf('-') !== -1 || block.phases.indexOf('H') !== -1 ) && block.phases.length === 1,
                                                                'panel-info'   : block.phases.length !== 1,
                                                                'blockactive' : activeBlock === block,
                                                                'block' : activeBlock !== block
                                                                }"
     draggable="true">

    <div class="panel-heading">
        <h3 class="panel-title">
            <span ng-if="block.grouping=='S'" class="glyphicon glyphicon-user" style="float: right;" aria-hidden="true" alt="Individuele werkvorm" title="Individuele werkvorm"></span>

            <span ng-if="block.grouping=='D'" class="glyphicon glyphicon-user" style="float: right;" aria-hidden="true" alt="Werkvorm in duo's" title="Werkvorm in duo's"></span>
            <span ng-if="block.grouping=='D'" class="glyphicon glyphicon-user" style="float: right;" aria-hidden="true" alt="Werkvorm in duo's" title="Werkvorm in duo's"></span>

            <span ng-if="block.grouping=='G'" class="glyphicon glyphicon-plus" style="float: right;" aria-hidden="true" alt="Werkvorm in kleine groepjes" title="Werkvorm in kleine groepjes"></span>
            <span ng-if="block.grouping=='G'" class="glyphicon glyphicon-user" style="float: right;" aria-hidden="true" alt="Werkvorm in kleine groepjes" title="Werkvorm in kleine groepjes"></span>

            <span ng-if="block.grouping=='C'" class="glyphicon glyphicon-asterisk" style="float: right;" aria-hidden="true" alt="Klassikale werkvorm" title="Klassikale werkvorm"></span>

            {{block.title}}
        </h3>
    </div>
    <div class="panel-body">

        <img ng-if="block.arcs.satisfaction.score == -3" src="images/arcsmeters/S-3.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.satisfaction.score == -2" src="images/arcsmeters/S-2.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.satisfaction.score == -1" src="images/arcsmeters/S-1.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.satisfaction.score == 0" src="images/arcsmeters/S0.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.satisfaction.score == 1" src="images/arcsmeters/S1.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.satisfaction.score == 2" src="images/arcsmeters/S2.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.satisfaction.score == 3" src="images/arcsmeters/S3.png" style="width: 12px; float: right;"/>

        <img ng-if="block.arcs.confidence.score == -3" src="images/arcsmeters/C-3.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.confidence.score == -2" src="images/arcsmeters/C-2.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.confidence.score == -1" src="images/arcsmeters/C-1.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.confidence.score == 0" src="images/arcsmeters/C0.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.confidence.score == 1" src="images/arcsmeters/C1.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.confidence.score == 2" src="images/arcsmeters/C2.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.confidence.score == 3" src="images/arcsmeters/C3.png" style="width: 12px; float: right;"/>

        <img ng-if="block.arcs.relevance.score == -3" src="images/arcsmeters/R-3.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.relevance.score == -2" src="images/arcsmeters/R-2.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.relevance.score == -1" src="images/arcsmeters/R-1.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.relevance.score == 0" src="images/arcsmeters/R0.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.relevance.score == 1" src="images/arcsmeters/R1.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.relevance.score == 2" src="images/arcsmeters/R2.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.relevance.score == 3" src="images/arcsmeters/R3.png" style="width: 12px; float: right;"/>

        <img ng-if="block.arcs.attention.score == -3" src="images/arcsmeters/A-3.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.attention.score == -2" src="images/arcsmeters/A-2.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.attention.score == -1" src="images/arcsmeters/A-1.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.attention.score == 0" src="images/arcsmeters/A0.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.attention.score == 1" src="images/arcsmeters/A1.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.attention.score == 2" src="images/arcsmeters/A2.png" style="width: 12px; float: right;"/>
        <img ng-if="block.arcs.attention.score == 3" src="images/arcsmeters/A3.png" style="width: 12px; float: right;"/>

        <div ng-if="activeBlock === block">
            <h5>Voorbereiding</h5>
            <div ng-class="{ 'active' : activeBlock === block }" ng-bind-html="block.preparation"></div>
        </div>

        <h5>Omschrijving</h5>
        <div ng-bind-html="block.description"></div>
    </div>
</div>