<div class="panel panel-info">
    <div class="panel-body">
        <!-- Overview selector -->
        <div class="btn-group btn-group-justified" role="group" aria-label="phaseselector">
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-info">Voorbereiding</button>
            </div>
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-info">De les</button>
            </div>
        </div>
    </div>

    <!-- Timeline -->
    <div style="overflow-y: auto; overflow-x: hidden; max-width: 100%; max-height:100%;">
        <div style="width: 180%; padding: 20px;">
            <timeline>
                <timeline-event ng-repeat="event in blocks" side="left">
                    <timeline-badge class="{{event.badgeClass}}">
                        <i class="glyphicon {{event.badgeIconClass}}"></i>
                    </timeline-badge>
                    <timeline-panel class="{{event.badgeClass}}">
                        <timeline-heading>
                            <h4>{{event.title}}</h4>
                        </timeline-heading>
                        <p>{{event.description}}</p>
                    </timeline-panel>
                </timeline-event>
            </timeline>
        </div>
    </div>
</div>