<div class="panel panel-info">
    <div class="panel-body">
        <!-- Overview selector -->
        <div class="btn-group btn-group-justified" role="group" aria-label="phaseselector">
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-info">Voorbereiding</button>
            </div>
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-info">De les</button>
            </div>
        </div>
    </div>

    <!-- Timeline -->
    <div style="overflow-y: auto; overflow-x: hidden; max-width: 100%; max-height:100%;">
        <div style="width: 180%; padding: 20px;">
            <timeline>
                <timeline-event ng-repeat="event in timeline" side="left">
                    <timeline-badge class="{{event.badgeClass}}" style="background-color: #FF0000;">
                        <span ng-if="event.block.grouping=='S'" class="glyphicon glyphicon-user" aria-hidden="true" alt="Individuele werkvorm" title="Individuele werkvorm"></span>

                        <span ng-if="event.block.grouping=='D'" class="glyphicon glyphicon-user" aria-hidden="true" alt="Werkvorm in duo's" title="Werkvorm in duo's"></span>
                        <span ng-if="event.block.grouping=='D'" class="glyphicon glyphicon-user" aria-hidden="true" alt="Werkvorm in duo's" title="Werkvorm in duo's"></span>

                        <span ng-if="event.block.grouping=='G'" class="glyphicon glyphicon-user" aria-hidden="true" alt="Werkvorm in kleine groepjes" title="Werkvorm in kleine groepjes"></span>
                        <span ng-if="event.block.grouping=='G'" class="glyphicon glyphicon-plus" aria-hidden="true" alt="Werkvorm in kleine groepjes" title="Werkvorm in kleine groepjes"></span>

                        <span ng-if="event.block.grouping=='C'" class="glyphicon glyphicon-asterisk" aria-hidden="true" alt="Klassikale werkvorm" title="Klassikale werkvorm"></span>
                    </timeline-badge>
                    <timeline-panel class="{{event.badgeClass}}" style="overflow-x: hidden;">
                        <timeline-heading>
                            <span class="label label-default">{{getLabel(event)}}</span>
                            <h5>
                                {{event.block.title}}
                            </h5>
                        </timeline-heading>
                        <h6>Beschrijving</h6>
                        <div ng-bind-html="event.block.description"></div>
                    </timeline-panel>
                </timeline-event>
            </timeline>
        </div>
    </div>
</div>