<div class="panel panel-default" ng-init="init()">
    <div class="panel-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                    <canvas id="doughnut" class="chart chart-doughnut img-responsive" chart-options="chartoptions" chart-colors="arcschart.colors" chart-data="arcschart.data" chart-labels="arcschart.labels">
                    </canvas>
                </div>
                <div class="col-md-4">
                    <canvas id="doughnut" class="chart chart-doughnut img-responsive" chart-options="chartoptions" chart-colors="groupingchart.colors" chart-data="groupingchart.data" chart-labels="groupingchart.labels">
                    </canvas>
                </div>
            </div>
        </div>
    </div>
</div>